---
latitude: 51.54362
longitude: -0.20008
map_zoom: 12
name: The Black Lion
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: 274 Kilburn High Road
  street2: ''
  state: ''
  city: London
  country: 
  zip_code: NW62BY
_hotel_id: THE731
_portal_id: required-but-empty
_ttweb_plugins_version: v2
_root_path: http://rtexpress-qa.ttaws.com/rt
